### PR TITLE
Made it compatibale with komposer2.0

### PR DESCRIPTION
**Pull request by arrygoo**
Following this issue: 
https://github.com/okgrow/accounts-ui-react/issues/4

### CODE REVIEW

**Comment by jamielob** [comment]
I'm assuming this is a breaking change, so I'd bump the version of the package too and add a note in the Readme.  Other than that it looks 👍 @arrygoo.

**Comment by arrygoo** [comment]
@jamielob Bumped to version 0.8 (or did you mean 1.0) and added a note to the readme. You think that looks good? I haven't been able to test it because I don't have a komposer2.0 project to try it on.

**Comment by arrygoo** [comment]
@jamielob FYI I've tried adding a test, but noticed that the test runs fine the first time, but stops working if you stop the server and restart. It continues working if you `meteor reset` or after any code change 🙃 . 
It's very peculiar because the bundled javascript is not being compiled consistently, and it looks different after you stop and start the server again.

The error that it's complaining about is usually something about one of the peer-dependencies, usually something like `Unable to lcoate ./lib/react`

**Comment by jamielob** [comment]
@arrygoo no clue what that's about! Maybe one of the testing gurus over there can put some eyes on it?

**Comment by arrygoo** [comment]
@jamielob I've spent few hours on it with different people. We concluded that it might be an issue with meteor since the builds are inconsistent (the actual bundled js is different in different situations described above). We're planning on posting this to meteor forums.

**Pull request merged**
